defmodule ExFleetYards.Repo.Migrations.Habitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:station_habitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text
      add :habitation_type, :text
      add :habitation_name, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :station_id,
          references(:stations,
            column: :id,
            name: "station_habitations_station_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:station_habitations, "station_habitations_station_id_fkey")

    drop table(:station_habitations)
  end
end