defmodule ExFleetYards.Repo.Migrations.Factions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:factions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text
      add :slug, :text, null: false
      add :code, :text, null: false
      add :color, :text
      add :rsi_id, :bigint
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:factions, [:code], name: "factions_unique_code_index")

    create unique_index(:factions, [:slug], name: "factions_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:factions, [:slug], name: "factions_unique_slug_index")

    drop_if_exists unique_index(:factions, [:code], name: "factions_unique_code_index")

    drop table(:factions)
  end
end