defmodule ExFleetYards.Repo.Migrations.Manufactureres do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:manufacturers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text
      add :slug, :text, null: false
      add :known_for, :text
      add :logo, :text
      add :description, :text
      add :rsi_id, :bigint
      add :code, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:manufacturers, [:slug], name: "manufacturers_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:manufacturers, [:slug], name: "manufacturers_unique_slug_index")

    drop table(:manufacturers)
  end
end