defmodule ExFleetYards.Repo.Migrations.Commodities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commodities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text
      add :slug, :text, null: false
      add :description, :text
      add :store_image, :text
      add :commodity_type, :bigint
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:commodities, [:slug], name: "commodities_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:commodities, [:slug], name: "commodities_unique_slug_index")

    drop table(:commodities)
  end
end