defmodule ExFleetYards.Repo.Migrations.Shops do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:shops, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text
      add :slug, :text, null: false
      add :description, :text
      add :store_image, :text
      add :shop_type, :text
      add :rental, :boolean, default: false
      add :refinery, :boolean, default: false
      add :buying, :boolean, default: false
      add :selling, :boolean, default: false
      add :location, :text
      add :hidden, :boolean, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :station_id,
          references(:stations,
            column: :id,
            name: "shops_station_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:shops, [:slug], where: "hidden = false", name: "shops_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:shops, [:slug], name: "shops_unique_slug_index")

    drop constraint(:shops, "shops_station_id_fkey")

    drop table(:shops)
  end
end