defmodule ExFleetYards.Repo.Migrations.Hardpoints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:model_hardpoints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text
      add :size, :bigint
      add :source, :text
      add :key, :text
      add :type, :text
      add :category, :text
      add :sub_category, :text
      add :group, :text
      add :details, :text
      add :mount, :text
      add :item_slot, :bigint
      add :item_slots, :bigint
      add :loadout_identifier, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :model_id,
          references(:models,
            column: :id,
            name: "model_hardpoints_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :component_id,
          references(:components,
            column: :id,
            name: "model_hardpoints_component_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:model_hardpoints, "model_hardpoints_model_id_fkey")

    drop constraint(:model_hardpoints, "model_hardpoints_component_id_fkey")

    drop table(:model_hardpoints)
  end
end