defmodule ExFleetYards.Repo.Migrations.Stations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text
      add :slug, :text, null: false
      add :station_type, :text
      add :hidden, :boolean, default: false
      add :store_image, :text
      add :description, :text
      add :location, :text
      add :cargo_hub, :boolean
      add :refinery, :boolean
      add :habitable, :boolean, default: true
      add :classification, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :celestial_object_id,
          references(:celestial_objects,
            column: :id,
            name: "stations_celestial_object_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:stations, [:slug],
             where: "hidden = false",
             name: "stations_unique_slug_index"
           )
  end

  def down do
    drop_if_exists unique_index(:stations, [:slug], name: "stations_unique_slug_index")

    drop constraint(:stations, "stations_celestial_object_id_fkey")

    drop table(:stations)
  end
end