defmodule ExFleetYards.Repo.Migrations.Model do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:models, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text
      add :slug, :text, null: false
      add :description, :text
      add :store_image, :text
      add :store_url, :text
      add :classification, :text
      add :rsi_id, :bigint
      add :production_status, :text
      add :production_note, :text
      add :focus, :text
      add :on_sale, :boolean
      add :pledge_price, :decimal
      add :length, :decimal
      add :beam, :decimal
      add :height, :decimal
      add :mass, :decimal
      add :cargo, :decimal
      add :size, :text
      add :scm_speed, :decimal
      add :afterburner_speed, :decimal
      add :cruise_speed, :decimal
      add :min_crew, :bigint
      add :max_crew, :bigint
      add :pitch_max, :decimal
      add :yaw_max, :decimal
      add :roll_max, :decimal
      add :xaxis_acceleration, :decimal
      add :yaxis_acceleration, :decimal
      add :zaxis_acceleration, :decimal
      add :fleetchart_image, :text
      add :store_images_updated_at, :utc_datetime
      add :last_updated_at, :utc_datetime
      add :last_pledge_price, :decimal
      add :rsi_name, :text
      add :rsi_slug, :text
      add :brochure, :text
      add :ground_speed, :decimal
      add :afterburner_ground_speed, :decimal
      add :notified, :boolean
      add :active, :boolean
      add :price, :decimal
      add :rsi_chassis_id, :bigint
      add :rsi_height, :decimal
      add :rsi_length, :decimal
      add :rsi_beam, :decimal
      add :rsi_cargo, :decimal
      add :dock_size, :bigint
      add :ground, :boolean
      add :rsi_max_crew, :bigint
      add :rsi_min_crew, :bigint
      add :rsi_scm_speed, :decimal
      add :rsi_afterburner_speed, :decimal
      add :rsi_pitch_max, :decimal
      add :rsi_yaw_max, :decimal
      add :rsi_roll_max, :decimal
      add :rsi_xaxis_acceleration, :decimal
      add :rsi_yaxis_acceleration, :decimal
      add :rsi_zaxis_acceleration, :decimal
      add :rsi_description, :text
      add :rsi_size, :text
      add :rsi_focus, :text
      add :rsi_classification, :text
      add :rsi_store_url, :text
      add :rsi_mass, :decimal
      add :sc_identifier, :text
      add :rsi_store_image, :text
      add :model_paints_count, :bigint
      add :images_count, :bigint
      add :videos_count, :bigint
      add :upgrade_kits_count, :bigint
      add :module_hardpoints_count, :bigint
      add :max_speed, :decimal
      add :speed, :decimal
      add :hydrogen_fuel_tank_size, :decimal
      add :quantum_fuel_tank_size, :decimal
      add :cargo_holds, :text
      add :hydrogen_fuel_tanks, :text
      add :quantum_fuel_tanks, :text
      add :holo, :text
      add :holo_colored, :boolean
      add :sales_page_url, :text
      add :top_view, :text
      add :side_view, :text
      add :erkul_identifier, :text
      add :fleetchart_offset_length, :decimal
      add :angled_view, :text
      add :fleetchart_image_height, :bigint
      add :fleetchart_image_width, :bigint
      add :angled_view_height, :bigint
      add :angled_view_width, :bigint
      add :top_view_height, :bigint
      add :top_view_width, :bigint
      add :side_view_height, :bigint
      add :side_view_width, :bigint
      add :hidden, :boolean, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :manufacturer_id,
          references(:manufacturers,
            column: :id,
            name: "models_manufacturer_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :base_model_id,
          references(:models,
            column: :id,
            name: "models_base_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:models, [:slug],
             where: "hidden = false",
             name: "models_unique_slug_index"
           )

    create table(:model_loaners, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :model_id,
          references(:models,
            column: :id,
            name: "model_loaners_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :loaner_id,
          references(:models,
            column: :id,
            name: "model_loaners_loaner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:docks) do
      add :model_id,
          references(:models,
            column: :id,
            name: "docks_model_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:docks, "docks_model_id_fkey")

    alter table(:docks) do
      remove :model_id
    end

    drop constraint(:model_loaners, "model_loaners_model_id_fkey")

    drop constraint(:model_loaners, "model_loaners_loaner_id_fkey")

    drop table(:model_loaners)

    drop_if_exists unique_index(:models, [:slug], name: "models_unique_slug_index")

    drop constraint(:models, "models_manufacturer_id_fkey")

    drop constraint(:models, "models_base_model_id_fkey")

    drop table(:models)
  end
end