defmodule ExFleetYards.Repo.Migrations.Affiliations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:faction_affiliations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :faction_id,
          references(:factions,
            column: :id,
            name: "faction_affiliations_faction_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :starsystem_id,
          references(:star_systems,
            column: :id,
            name: "faction_affiliations_starsystem_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :celestial_object_id,
          references(:celestial_objects,
            column: :id,
            name: "faction_affiliations_celestial_object_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:faction_affiliations, "faction_affiliations_faction_id_fkey")

    drop constraint(:faction_affiliations, "faction_affiliations_starsystem_id_fkey")

    drop constraint(:faction_affiliations, "faction_affiliations_celestial_object_id_fkey")

    drop table(:faction_affiliations)
  end
end
