defmodule ExFleetYards.Repo.Migrations.Docks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:docks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :dock_type, :text
      add :name, :text
      add :max_ship_size, :text
      add :min_ship_size, :text
      add :ship_size, :text
      add :height, :float
      add :length, :float
      add :group, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :station_id,
          references(:stations,
            column: :id,
            name: "docks_station_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:docks, "docks_station_id_fkey")

    drop table(:docks)
  end
end