defmodule ExFleetYards.Repo.Migrations.StarSystem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:star_systems, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text
      add :slug, :text, null: false
      add :sotre_imge, :text
      add :rsi_id, :bigint
      add :code, :text
      add :position_x, :bigint
      add :position_y, :bigint
      add :position_z, :bigint
      add :status, :text
      add :last_updated_at, :utc_datetime_usec
      add :system_type, :text
      add :aggregated_size, :bigint
      add :aggregated_population, :bigint
      add :aggregated_economy, :bigint
      add :aggregated_danger, :bigint
      add :hidden, :boolean, default: false
      add :description, :text
      add :map, :text
      add :map_x, :bigint
      add :map_y, :bigint
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:star_systems, [:slug], name: "star_systems_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:star_systems, [:slug], name: "star_systems_unique_slug_index")

    drop table(:star_systems)
  end
end