defmodule ExFleetYards.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :locale, :text, default: "en"
      add :username, :text, null: false
      add :email, :citext, null: false
      add :password_hash, :text
      add :last_sign_in_at, :utc_datetime_usec
      add :last_sign_in_ip, :text
      add :confiremd_at, :utc_datetime_usec
      add :deactivated, :boolean, default: false
      add :sale_notify, :boolean, default: false
      add :tracking, :boolean, default: false
      add :public_hangar, :boolean, default: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:users, [:email], name: "users_email_index")

    create unique_index(:users, [:id], name: "users_id_index")

    create unique_index(:users, [:username], name: "users_username_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:username], name: "users_username_index")

    drop_if_exists unique_index(:users, [:id], name: "users_id_index")

    drop_if_exists unique_index(:users, [:email], name: "users_email_index")

    drop table(:users)
  end
end
