import Config

# Configure your database
if System.get_env("FLEETYARDS_IN_DEVENV") == "1" do
else
  config :ex_fleet_yards, ExFleetYards.Repo,
    username: "fleet_yards_dev",
    password: "fleet_yards_dev"
end

config :ex_fleet_yards, ExFleetYards.Repo,
  database: "fleet_yards_dev",
  hostname: "localhost",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :ex_fleet_yards_web, ExFleetYardsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [
    ip: {127, 0, 0, 1},
    port: 4000
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "zMnmcNSJebHEPCJqrtztxeTVMEWfciC0cxNuEFZWRZFx2/QA4Ull5nkkLwqQBRQ6",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

config :ex_fleet_yards_api, ExFleetYardsApi.Endpoint,
  http: [
    ip: {127, 0, 0, 1},
    port: 4001
  ],
  secret_key_base: "zMnmcNSJebHEPCJqrtztxeTVMEWfciC0cxNuEFZWRZFx2/QA4Ull5nkkLwqQBRQ6",
  live_view: [signing_salt: "F07EFQKnybYwDgCO"]

config :ex_fleet_yards_auth, ExFleetYardsAuth.Endpoint,
  http: [
    ip: {127, 0, 0, 1},
    port: 4002
  ],
  secret_key_base: "zMnmcNSJebHEPCJqrtztxeTVMEWfciC0cxNuEFZWRZFx2/QA4Ull5nkkLwqQBRQ6",
  live_view: [signing_salt: "F07EFQKnybYwDgCO"],
  check_origin: false,
  code_reloader: true,
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:auth, args)
    esbuild: {Esbuild, :install_and_run, [:auth, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:auth, ~w(--watch)]}
  ]

config :joken,
  default_signer: [
    signer_alg: "HS256",
    key_octet:
      "M9wSYbVcLFTHIsbG94wj1b8VdwsTh2QPlCrFxyAFwg7s7/kkqfTXQc7lHvfYg+zdYkbl3ETjDKsH0Tcqq5bNEQ=="
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ex_fleet_yards_web, ExFleetYardsWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ex_fleet_yards_web/(live|views)/.*(ex)$",
      ~r"lib/ex_fleet_yards_web/templates/.*(eex)$"
    ]
  ]

config :ex_fleet_yards_auth, ExFleetYardsAuth.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ex_fleet_yards_auth/(live|views)/.*(ex)$",
      ~r"lib/ex_fleet_yards_auth/controllers/.*_html/.*(heex)$",
      ~r"lib/ex_fleet_yards_auth/components/.*(ex)$"
    ]
  ],
  reloadable_apps: [:ex_fleet_yards_auth, :ex_fleet_yards]

# Do not include metadata nor timestamps in development logs
config :logger, :console,
  format: "$metadata[$level] $message\n",
  metadata: [:request_id, :user_id],
  compile_time_purge_matching: [
    [level_lower_than: :debug]
  ]

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Disable openapi cache for development
config :open_api_spex, :cache_adapter, OpenApiSpex.Plug.NoneCache

config :ex_fleet_yards, ExFleetYards.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1", key: Base.decode64!("fGG2AWVqsTc53CpCBmChtOk+G9LyPCmvApiGtPQW9wI=")}
  ]

config :appsignal, :config,
  active: false,
  env: :dev
